### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by ashmalzahra** [anderCM/CC-Global#2]
In this issue we gave @anderCM  some feedback 

@ashmalzahra 

**Highlights:**
- Clean code, easy to navigate.
- All features work perfectly.

**Recommendations:**
- kindly rearrange navbar width since it's messing with the `html` body structure
 
 @Uthmanbello 

**Recommendations:**
- In 'index.js' from line 9, kindly rearrange the `programs` array so that it becomes more readable.

**Comment by anderCM** [comment]
Issue fixed in this [PR](https://github.com/anderCM/CC-Global/pull/3)
